// Generated by Babel
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = fingerprint;

var _md5File = require("md5-file");

var _md5File2 = _interopRequireDefault(_md5File);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function fingerprint(file) {
  return ["tus", _md5File2.default.sync(file.path)].join("-");
} /**
   * Generate a fingerprint for a file which will be used the store the endpoint
   *
   * @param {File} file
   * @return {String}
   */